package com.sarvam_ai.sarvam_sdk.api.api_interfaces

import com.sarvam_ai.sarvam_sdk.models.Chat
import com.squareup.moshi.JsonClass

/**
 * Represents a chat request payload for Sarvam AI.
 *
 * @param model The model ID to use for completions. Defaults to SARVAM_M.
 * @param stream If true, enables streaming responses via SSE.
 * @param messages The list of chat messages representing conversation history.
 */
@JsonClass(generateAdapter = true)
data class ChatRequest(
    val model: String = Chat.SARVAM_M.modelId,
    val stream: Boolean = true,
    val messages: List<Message>
)

/**
 * Represents a single chat message in the conversation.
 *
 * @param role The role of the sender (system, user, assistant).
 * @param content The text content of the message.
 */
@JsonClass(generateAdapter = true)
data class Message(
    val role: String,
    val content: String
)

/**
 * Common chat roles used in Sarvam AI.
 */
enum class ROLE(val value: String) {
    SYSTEM("system"),
    USER("user"),
    ASSISTANT("assistant")
}

/**
 * Represents the full chat completion response from Sarvam AI.
 *
 * @param choices The list of generated completions.
 */
@JsonClass(generateAdapter = true)
data class ChatResponse(
    val choices: List<Choice>
)

/**
 * Represents an individual choice within the completion response.
 *
 * @param message The message generated by the assistant.
 */
@JsonClass(generateAdapter = true)
data class Choice(
    val message: Message
)
